#!/bin/sh
#
### BEGIN INIT INFO
# Provides: monitor
# Required-Start: dhcpd httpd mysqld dnsmasq
# Required-Stop: 
# Default-Start: 3 
# Default-Stop: 0 1 6
# Short-Description: The Hotel monitor
# Description: The Hotel monitor
### END INIT INFO

# Source function library.
. /etc/init.d/functions

PATH=$PATH:/usr/local/bin

append()
{
	need mysqld
}

depend()
{
	need mysqld
}

start () {
	echo -n $"Starting $prog: "

	monitor --daemon
	
	echo "OK"
	return 0
}

stop () {
	# stop daemon
	echo -n $"Stopping $prog: "
	killall -2 monitor > /dev/NULL 2>/dev/null
	echo "OK"
	return 0
}

restart() {
	stop
	start	
	return 0
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		restart
	;;
	*)
	echo $"Usage: $prog {start|stop|restart}"
	exit 3
esac

exit $RETVAL
